### ISSUE TITLE
Error "AssertionError: 32 != 4" while training

### ISSUE THREAD

**Issue by AchmadFachturrohman** [phizaz/diffae#48]
Epoch 1:  14% 2500/17500 [51:03<5:06:23,  1.23s/it, loss=0.0144, v_num=]Traceback (most recent call last):
  File "/content/diffae/run_ffhq256.py", line 10, in <module>
    train(conf, gpus=gpus, nodes=nodes)
  File "/content/diffae/experiment.py", line 937, in train
    trainer.fit(model)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 230, in advance
    self.trainer._call_lightning_module_hook("on_train_batch_end", batch_end_outputs, batch, batch_idx)
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/content/diffae/experiment.py", line 429, in on_train_batch_end
    self.log_sample(x_start=imgs)
  File "/content/diffae/experiment.py", line 569, in log_sample
    do(self.model, '', use_xstart=True, save_real=True)
  File "/content/diffae/experiment.py", line 498, in do
    gen = self.eval_sampler.sample(model=model,
  File "/content/diffae/diffusion/base.py", line 208, in sample
    return self.ddim_sample_loop(model,
  File "/content/diffae/diffusion/base.py", line 735, in ddim_sample_loop
    for sample in self.ddim_sample_loop_progressive(
  File "/content/diffae/diffusion/base.py", line 795, in ddim_sample_loop_progressive
    out = self.ddim_sample(
  File "/content/diffae/diffusion/base.py", line 600, in ddim_sample
    out = self.p_mean_variance(
  File "/content/diffae/diffusion/diffusion.py", line 96, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args,
  File "/content/diffae/diffusion/base.py", line 307, in p_mean_variance
    model_forward = model.forward(x=x,
  File "/content/diffae/diffusion/diffusion.py", line 153, in forward
    return self.model(x=x, t=do(t), t_cond=t_cond, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/diffae/model/unet_autoenc.py", line 149, in forward
    assert len(x) == len(x_start), f'{len(x)} != {len(x_start)}'
AssertionError: 32 != 4
Epoch 1:  14%|█▍        | 2500/17500 [51:21<5:08:09,  1.23s/it, loss=0.0144, v_num=]

I got an error like that while I tried to resume the training ffhq256. How do I fix it?

**Comment by xhh12381** [comment]
You should change the batch_size to 4 in the config.py

**Comment by AchmadFachturrohman** [comment]
Solved. Thankyou sir

Pada tanggal Sab, 18 Mar 2023 12.48, Adam ***@***.***>
menulis:

**Comment by AdaMesh** [comment]
I solve this issue by changing experiment.py line 461 to 
`batch_size = min(len(all_x_T), self.conf.batch_size_eval, len(x_start))`

**Comment by LeoniusChen** [comment]
I solve this issue by changing experiment.py line 461 to 
`batch_size = min(len(all_x_T), self.conf.batch_size_eval, len(x_start))`
